/**
 * Tpay.com Technical Documentation
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: pt@tpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Result from './Result';
import TransactionErrorCodes from './TransactionErrorCodes';

/**
 * The CreateResponse model module.
 * @module model/CreateResponse
 * @version 1.2.0
 */
class CreateResponse {
    /**
     * Constructs a new <code>CreateResponse</code>.
     * @alias module:model/CreateResponse
     * @param result {module:model/Result} 
     */
    constructor(result) { 
        
        CreateResponse.initialize(this, result);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, result) { 
        obj['result'] = result;
    }

    /**
     * Constructs a <code>CreateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateResponse} obj Optional instance to populate.
     * @return {module:model/CreateResponse} The populated <code>CreateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = Result.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('err')) {
                obj['err'] = TransactionErrorCodes.constructFromObject(data['err']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('account_number')) {
                obj['account_number'] = ApiClient.convertToType(data['account_number'], 'Number');
            }
            if (data.hasOwnProperty('online')) {
                obj['online'] = ApiClient.convertToType(data['online'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('desc')) {
                obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Result} result
 */
CreateResponse.prototype['result'] = undefined;

/**
 * @member {module:model/TransactionErrorCodes} err
 */
CreateResponse.prototype['err'] = undefined;

/**
 * Transaction title
 * @member {String} title
 */
CreateResponse.prototype['title'] = undefined;

/**
 * transaction amount casted to float
 * @member {Number} amount
 */
CreateResponse.prototype['amount'] = undefined;

/**
 * bank account number (only for manual bank transfers)
 * @member {Number} account_number
 */
CreateResponse.prototype['account_number'] = undefined;

/**
 * Booking payments online indicator
 * @member {Number} online
 */
CreateResponse.prototype['online'] = undefined;

/**
 * Link to transaction (for redirecting to payment)
 * @member {String} url
 */
CreateResponse.prototype['url'] = undefined;

/**
 * optional field, contains names of invalid fields.
 * @member {String} desc
 */
CreateResponse.prototype['desc'] = undefined;






export default CreateResponse;

