/**
 * Tpay.com Technical Documentation
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: pt@tpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Language.
* @enum {}
* @readonly
*/
export default class Language {
    
        /**
         * value: "pl"
         * @const
         */
        "pl" = "pl";

    
        /**
         * value: "en"
         * @const
         */
        "en" = "en";

    
        /**
         * value: "fr"
         * @const
         */
        "fr" = "fr";

    
        /**
         * value: "es"
         * @const
         */
        "es" = "es";

    
        /**
         * value: "it"
         * @const
         */
        "it" = "it";

    
        /**
         * value: "ru"
         * @const
         */
        "ru" = "ru";

    
        /**
         * value: "de"
         * @const
         */
        "de" = "de";

    
        /**
         * value: "uk"
         * @const
         */
        "uk" = "uk";

    
        /**
         * value: "ro"
         * @const
         */
        "ro" = "ro";

    
        /**
         * value: "hu"
         * @const
         */
        "hu" = "hu";

    
        /**
         * value: "cs"
         * @const
         */
        "cs" = "cs";

    
        /**
         * value: "bg"
         * @const
         */
        "bg" = "bg";

    
        /**
         * value: "hr"
         * @const
         */
        "hr" = "hr";

    

    /**
    * Returns a <code>Language</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Language} The enum <code>Language</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

