/**
 * Tpay.com Technical Documentation
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: pt@tpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MasspaymentErrDesc.
* @enum {}
* @readonly
*/
export default class MasspaymentErrDesc {
    
        /**
         * value: "File that has been sent is not CSV file"
         * @const
         */
        "File that has been sent is not CSV file" = "File that has been sent is not CSV file";

    
        /**
         * value: "Incorrect checksum (sign)"
         * @const
         */
        "Incorrect checksum (sign)" = "Incorrect checksum (sign)";

    
        /**
         * value: "Incorrect line format"
         * @const
         */
        "Incorrect line format" = "Incorrect line format";

    
        /**
         * value: "Incorrect bank account number"
         * @const
         */
        "Incorrect bank account number" = "Incorrect bank account number";

    
        /**
         * value: "Name of the receiver must not be empty"
         * @const
         */
        "Name of the receiver must not be empty" = "Name of the receiver must not be empty";

    
        /**
         * value: "Name of the receiver 1 is too long – max, 35 characters"
         * @const
         */
        "Name of the receiver 1 is too long – max, 35 characters" = "Name of the receiver 1 is too long – max, 35 characters";

    
        /**
         * value: "Name of the receiver 2 is too long – max, 35 characters"
         * @const
         */
        "Name of the receiver 2 is too long – max, 35 characters" = "Name of the receiver 2 is too long – max, 35 characters";

    
        /**
         * value: "Name of the receiver 3 is too long – max, 35 characters"
         * @const
         */
        "Name of the receiver 3 is too long – max, 35 characters" = "Name of the receiver 3 is too long – max, 35 characters";

    
        /**
         * value: "Name of the receiver 4 is too long – max, 35 characters"
         * @const
         */
        "Name of the receiver 4 is too long – max, 35 characters" = "Name of the receiver 4 is too long – max, 35 characters";

    
        /**
         * value: "Incorrect amount format"
         * @const
         */
        "Incorrect amount format" = "Incorrect amount format";

    
        /**
         * value: "Payment title field must not be empty"
         * @const
         */
        "Payment title field must not be empty" = "Payment title field must not be empty";

    
        /**
         * value: "Payment title field 1 is too long – max. 35 characters"
         * @const
         */
        "Payment title field 1 is too long – max. 35 characters" = "Payment title field 1 is too long – max. 35 characters";

    
        /**
         * value: "Payment title field 2 is too long – max. 35 characters"
         * @const
         */
        "Payment title field 2 is too long – max. 35 characters" = "Payment title field 2 is too long – max. 35 characters";

    
        /**
         * value: "Internal error"
         * @const
         */
        "Internal error" = "Internal error";

    
        /**
         * value: "Failed to load CSV file"
         * @const
         */
        "Failed to load CSV file" = "Failed to load CSV file";

    
        /**
         * value: "Transfer processing error"
         * @const
         */
        "Transfer processing error" = "Transfer processing error";

    
        /**
         * value: "Incorrect pack_id or the package has not been found"
         * @const
         */
        "Incorrect pack_id or the package has not been found" = "Incorrect pack_id or the package has not been found";

    
        /**
         * value: "Package authorization error"
         * @const
         */
        "Package authorization error" = "Package authorization error";

    
        /**
         * value: "Insufficient funds for package autorization"
         * @const
         */
        "Insufficient funds for package autorization" = "Insufficient funds for package autorization";

    
        /**
         * value: "Package has already been authorized"
         * @const
         */
        "Package has already been authorized" = "Package has already been authorized";

    
        /**
         * value: "General error"
         * @const
         */
        "General error" = "General error";

    
        /**
         * value: "Login error (incorrent key or api_password)"
         * @const
         */
        "Login error (incorrent key or api_password)" = "Login error (incorrent key or api_password)";

    
        /**
         * value: "No such method"
         * @const
         */
        "No such method" = "No such method";

    
        /**
         * value: "Access disabled"
         * @const
         */
        "Access disabled" = "Access disabled";

    
        /**
         * value: "Access denied (via Merchant Panel settings)"
         * @const
         */
        "Access denied (via Merchant Panel settings)" = "Access denied (via Merchant Panel settings)";

    

    /**
    * Returns a <code>MasspaymentErrDesc</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MasspaymentErrDesc} The enum <code>MasspaymentErrDesc</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

