/**
 * Tpay.com Technical Documentation
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: pt@tpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MasspaymentErrCode.
* @enum {}
* @readonly
*/
export default class MasspaymentErrCode {
    
        /**
         * value: "ERR4"
         * @const
         */
        "ERR4" = "ERR4";

    
        /**
         * value: "ERR6"
         * @const
         */
        "ERR6" = "ERR6";

    
        /**
         * value: "ERR7"
         * @const
         */
        "ERR7" = "ERR7";

    
        /**
         * value: "ERR8"
         * @const
         */
        "ERR8" = "ERR8";

    
        /**
         * value: "ERR9"
         * @const
         */
        "ERR9" = "ERR9";

    
        /**
         * value: "ERR10"
         * @const
         */
        "ERR10" = "ERR10";

    
        /**
         * value: "ERR11"
         * @const
         */
        "ERR11" = "ERR11";

    
        /**
         * value: "ERR12"
         * @const
         */
        "ERR12" = "ERR12";

    
        /**
         * value: "ERR13"
         * @const
         */
        "ERR13" = "ERR13";

    
        /**
         * value: "ERR14"
         * @const
         */
        "ERR14" = "ERR14";

    
        /**
         * value: "ERR15"
         * @const
         */
        "ERR15" = "ERR15";

    
        /**
         * value: "ERR16"
         * @const
         */
        "ERR16" = "ERR16";

    
        /**
         * value: "ERR17"
         * @const
         */
        "ERR17" = "ERR17";

    
        /**
         * value: "ERR18"
         * @const
         */
        "ERR18" = "ERR18";

    
        /**
         * value: "ERR19"
         * @const
         */
        "ERR19" = "ERR19";

    
        /**
         * value: "ERR20"
         * @const
         */
        "ERR20" = "ERR20";

    
        /**
         * value: "ERR21"
         * @const
         */
        "ERR21" = "ERR21";

    
        /**
         * value: "ERR22"
         * @const
         */
        "ERR22" = "ERR22";

    
        /**
         * value: "ERR23"
         * @const
         */
        "ERR23" = "ERR23";

    
        /**
         * value: "ERR24"
         * @const
         */
        "ERR24" = "ERR24";

    
        /**
         * value: "ERR99"
         * @const
         */
        "ERR99" = "ERR99";

    
        /**
         * value: "ERR98"
         * @const
         */
        "ERR98" = "ERR98";

    
        /**
         * value: "ERR97"
         * @const
         */
        "ERR97" = "ERR97";

    
        /**
         * value: "ERR31"
         * @const
         */
        "ERR31" = "ERR31";

    
        /**
         * value: "ERR32"
         * @const
         */
        "ERR32" = "ERR32";

    

    /**
    * Returns a <code>MasspaymentErrCode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MasspaymentErrCode} The enum <code>MasspaymentErrCode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

