/**
 * Tpay.com Technical Documentation
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: pt@tpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Language from './Language';

/**
 * The RefundFields model module.
 * @module model/RefundFields
 * @version 1.2.0
 */
class RefundFields {
    /**
     * Constructs a new <code>RefundFields</code>.
     * @alias module:model/RefundFields
     * @param desc {String} 
     * @param apiPassword {String} API password.
     * @param sign {String} Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + desc + amount + currency + language + verification code); where + means concatenation with ampersand symbol. ie. currency + language = 985&pl
     */
    constructor(desc, apiPassword, sign) { 
        
        RefundFields.initialize(this, desc, apiPassword, sign);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, desc, apiPassword, sign) { 
        obj['desc'] = desc;
        obj['api_password'] = apiPassword;
        obj['sign'] = sign;
    }

    /**
     * Constructs a <code>RefundFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RefundFields} obj Optional instance to populate.
     * @return {module:model/RefundFields} The populated <code>RefundFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RefundFields();

            if (data.hasOwnProperty('cli_auth')) {
                obj['cli_auth'] = ApiClient.convertToType(data['cli_auth'], 'String');
            }
            if (data.hasOwnProperty('sale_auth')) {
                obj['sale_auth'] = ApiClient.convertToType(data['sale_auth'], 'String');
            }
            if (data.hasOwnProperty('desc')) {
                obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = Language.constructFromObject(data['language']);
            }
            if (data.hasOwnProperty('api_password')) {
                obj['api_password'] = ApiClient.convertToType(data['api_password'], 'String');
            }
            if (data.hasOwnProperty('sign')) {
                obj['sign'] = ApiClient.convertToType(data['sign'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Client token
 * @member {String} cli_auth
 */
RefundFields.prototype['cli_auth'] = undefined;

/**
 * Transaction id in tpay.com system
 * @member {String} sale_auth
 */
RefundFields.prototype['sale_auth'] = undefined;

/**
 * @member {String} desc
 */
RefundFields.prototype['desc'] = undefined;

/**
 * transaction currency in ISO numeric format
 * @member {Number} currency
 * @default 985
 */
RefundFields.prototype['currency'] = 985;

/**
 * transaction amount casted to float
 * @member {Number} amount
 */
RefundFields.prototype['amount'] = undefined;

/**
 * @member {module:model/Language} language
 */
RefundFields.prototype['language'] = undefined;

/**
 * API password.
 * @member {String} api_password
 */
RefundFields.prototype['api_password'] = undefined;

/**
 * Sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + desc + amount + currency + language + verification code); where + means concatenation with ampersand symbol. ie. currency + language = 985&pl
 * @member {String} sign
 */
RefundFields.prototype['sign'] = undefined;






export default RefundFields;

