/**
 * Tpay.com Technical Documentation
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: pt@tpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SaleFields model module.
 * @module model/SaleFields
 * @version 1.2.0
 */
class SaleFields {
    /**
     * Constructs a new <code>SaleFields</code>.
     * @alias module:model/SaleFields
     * @param cliAuth {String} Client token
     * @param saleAuth {String} Transaction id in tpay.com system
     * @param apiPassword {String} API password.
     * @param sign {String} Request sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + verification code); where + means concatenation with ampersand symbol. ie. name + email = john done&john.doe@example.com. Passed cli_auth has to match with cli_auth used while creating sale in presale method. 
     */
    constructor(cliAuth, saleAuth, apiPassword, sign) { 
        
        SaleFields.initialize(this, cliAuth, saleAuth, apiPassword, sign);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cliAuth, saleAuth, apiPassword, sign) { 
        obj['cli_auth'] = cliAuth;
        obj['sale_auth'] = saleAuth;
        obj['api_password'] = apiPassword;
        obj['sign'] = sign;
    }

    /**
     * Constructs a <code>SaleFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SaleFields} obj Optional instance to populate.
     * @return {module:model/SaleFields} The populated <code>SaleFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SaleFields();

            if (data.hasOwnProperty('cli_auth')) {
                obj['cli_auth'] = ApiClient.convertToType(data['cli_auth'], 'String');
            }
            if (data.hasOwnProperty('sale_auth')) {
                obj['sale_auth'] = ApiClient.convertToType(data['sale_auth'], 'String');
            }
            if (data.hasOwnProperty('api_password')) {
                obj['api_password'] = ApiClient.convertToType(data['api_password'], 'String');
            }
            if (data.hasOwnProperty('sign')) {
                obj['sign'] = ApiClient.convertToType(data['sign'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Client token
 * @member {String} cli_auth
 */
SaleFields.prototype['cli_auth'] = undefined;

/**
 * Transaction id in tpay.com system
 * @member {String} sale_auth
 */
SaleFields.prototype['sale_auth'] = undefined;

/**
 * API password.
 * @member {String} api_password
 */
SaleFields.prototype['api_password'] = undefined;

/**
 * Request sign is calculated from cryptographic hash function set in Merchant’s Panel (default SHA-1): hash_alg (method + cli_auth + sale_auth + verification code); where + means concatenation with ampersand symbol. ie. name + email = john done&john.doe@example.com. Passed cli_auth has to match with cli_auth used while creating sale in presale method. 
 * @member {String} sign
 */
SaleFields.prototype['sign'] = undefined;






export default SaleFields;

