/**
 * Tpay.com Technical Documentation
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: pt@tpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Result from './Result';

/**
 * The SaleResponse model module.
 * @module model/SaleResponse
 * @version 1.2.0
 */
class SaleResponse {
    /**
     * Constructs a new <code>SaleResponse</code>.
     * @alias module:model/SaleResponse
     * @param result {module:model/Result} 
     * @param saleAuth {String} Transaction id in tpay.com system
     * @param currency {Number} transaction currency in ISO numeric format
     * @param amount {Number} transaction amount casted to float
     * @param status {module:model/SaleResponse.StatusEnum} 
     * @param sign {String} Response sign = hash_alg(test_mode + sale_auth + cli_auth + currency + amount + date + status + reason + verification code)
     */
    constructor(result, saleAuth, currency, amount, status, sign) { 
        
        SaleResponse.initialize(this, result, saleAuth, currency, amount, status, sign);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, result, saleAuth, currency, amount, status, sign) { 
        obj['result'] = result;
        obj['sale_auth'] = saleAuth;
        obj['currency'] = currency || 985;
        obj['amount'] = amount;
        obj['status'] = status;
        obj['sign'] = sign;
    }

    /**
     * Constructs a <code>SaleResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SaleResponse} obj Optional instance to populate.
     * @return {module:model/SaleResponse} The populated <code>SaleResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SaleResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = Result.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('test_mode')) {
                obj['test_mode'] = ApiClient.convertToType(data['test_mode'], 'String');
            }
            if (data.hasOwnProperty('sale_auth')) {
                obj['sale_auth'] = ApiClient.convertToType(data['sale_auth'], 'String');
            }
            if (data.hasOwnProperty('cli_auth')) {
                obj['cli_auth'] = ApiClient.convertToType(data['cli_auth'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('sign')) {
                obj['sign'] = ApiClient.convertToType(data['sign'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Result} result
 */
SaleResponse.prototype['result'] = undefined;

/**
 * This parameter is present in response and included in sign calculation only when the merchant account is in test mode.
 * @member {String} test_mode
 */
SaleResponse.prototype['test_mode'] = undefined;

/**
 * Transaction id in tpay.com system
 * @member {String} sale_auth
 */
SaleResponse.prototype['sale_auth'] = undefined;

/**
 * Client token
 * @member {String} cli_auth
 */
SaleResponse.prototype['cli_auth'] = undefined;

/**
 * transaction currency in ISO numeric format
 * @member {Number} currency
 * @default 985
 */
SaleResponse.prototype['currency'] = 985;

/**
 * transaction amount casted to float
 * @member {Number} amount
 */
SaleResponse.prototype['amount'] = undefined;

/**
 * Date of payment
 * @member {String} date
 */
SaleResponse.prototype['date'] = undefined;

/**
 * @member {module:model/SaleResponse.StatusEnum} status
 */
SaleResponse.prototype['status'] = undefined;

/**
 * Acquirer (Elavon / eService) rejection code - see \"Card Payments Rejection Codes\" for more details
 * @member {String} reason
 */
SaleResponse.prototype['reason'] = undefined;

/**
 * Response sign = hash_alg(test_mode + sale_auth + cli_auth + currency + amount + date + status + reason + verification code)
 * @member {String} sign
 */
SaleResponse.prototype['sign'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
SaleResponse['StatusEnum'] = {

    /**
     * value: "correct"
     * @const
     */
    "correct": "correct",

    /**
     * value: "declined"
     * @const
     */
    "declined": "declined",

    /**
     * value: "done"
     * @const
     */
    "done": "done"
};



export default SaleResponse;

