/**
 * Tpay.com Technical Documentation
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: pt@tpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Language from './Language';
import Onetimer from './Onetimer';

/**
 * The SecuresaleFields model module.
 * @module model/SecuresaleFields
 * @version 1.2.0
 */
class SecuresaleFields {
    /**
     * Constructs a new <code>SecuresaleFields</code>.
     * @alias module:model/SecuresaleFields
     * @param name {String} customer name
     * @param email {String} customer email
     * @param desc {String} transaction description
     * @param amount {Number} transaction amount casted to float
     * @param apiPassword {String} API password.
     * @param sign {String} Sign is calculated from cryptographic hash function set in Merchant panel (default SHA-1) hash_alg (method + card + name + email + desc + amount + currency + order_id + onetimer + language + enable_pow_url + verification code) where + means concatenation with ampersand symbol. ie. name + email = john done&john.doe@example.com
     * @param currency {Number} transaction currency in ISO numeric format
     * @param card {String} Card hash calculated by schema described in method description
     */
    constructor(name, email, desc, amount, apiPassword, sign, currency, card) { 
        
        SecuresaleFields.initialize(this, name, email, desc, amount, apiPassword, sign, currency, card);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, email, desc, amount, apiPassword, sign, currency, card) { 
        obj['name'] = name;
        obj['email'] = email;
        obj['desc'] = desc;
        obj['amount'] = amount;
        obj['api_password'] = apiPassword;
        obj['sign'] = sign;
        obj['currency'] = currency || 985;
        obj['card'] = card;
    }

    /**
     * Constructs a <code>SecuresaleFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecuresaleFields} obj Optional instance to populate.
     * @return {module:model/SecuresaleFields} The populated <code>SecuresaleFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecuresaleFields();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('desc')) {
                obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('api_password')) {
                obj['api_password'] = ApiClient.convertToType(data['api_password'], 'String');
            }
            if (data.hasOwnProperty('sign')) {
                obj['sign'] = ApiClient.convertToType(data['sign'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'Number');
            }
            if (data.hasOwnProperty('onetimer')) {
                obj['onetimer'] = Onetimer.constructFromObject(data['onetimer']);
            }
            if (data.hasOwnProperty('pow_url')) {
                obj['pow_url'] = ApiClient.convertToType(data['pow_url'], 'String');
            }
            if (data.hasOwnProperty('pow_url_blad')) {
                obj['pow_url_blad'] = ApiClient.convertToType(data['pow_url_blad'], 'String');
            }
            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = ApiClient.convertToType(data['order_id'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = Language.constructFromObject(data['language']);
            }
            if (data.hasOwnProperty('enable_pow_url')) {
                obj['enable_pow_url'] = ApiClient.convertToType(data['enable_pow_url'], 'Number');
            }
            if (data.hasOwnProperty('card')) {
                obj['card'] = ApiClient.convertToType(data['card'], 'String');
            }
        }
        return obj;
    }


}

/**
 * customer name
 * @member {String} name
 */
SecuresaleFields.prototype['name'] = undefined;

/**
 * customer email
 * @member {String} email
 */
SecuresaleFields.prototype['email'] = undefined;

/**
 * transaction description
 * @member {String} desc
 */
SecuresaleFields.prototype['desc'] = undefined;

/**
 * transaction amount casted to float
 * @member {Number} amount
 */
SecuresaleFields.prototype['amount'] = undefined;

/**
 * API password.
 * @member {String} api_password
 */
SecuresaleFields.prototype['api_password'] = undefined;

/**
 * Sign is calculated from cryptographic hash function set in Merchant panel (default SHA-1) hash_alg (method + card + name + email + desc + amount + currency + order_id + onetimer + language + enable_pow_url + verification code) where + means concatenation with ampersand symbol. ie. name + email = john done&john.doe@example.com
 * @member {String} sign
 */
SecuresaleFields.prototype['sign'] = undefined;

/**
 * transaction currency in ISO numeric format
 * @member {Number} currency
 * @default 985
 */
SecuresaleFields.prototype['currency'] = 985;

/**
 * @member {module:model/Onetimer} onetimer
 */
SecuresaleFields.prototype['onetimer'] = undefined;

/**
 * url to redirect customer in case of payment success
 * @member {String} pow_url
 */
SecuresaleFields.prototype['pow_url'] = undefined;

/**
 * url to redirect customer in case of payment failure
 * @member {String} pow_url_blad
 */
SecuresaleFields.prototype['pow_url_blad'] = undefined;

/**
 * merchant order ID used to recognise payment
 * @member {String} order_id
 */
SecuresaleFields.prototype['order_id'] = undefined;

/**
 * @member {module:model/Language} language
 */
SecuresaleFields.prototype['language'] = undefined;

/**
 * @member {Number} enable_pow_url
 */
SecuresaleFields.prototype['enable_pow_url'] = undefined;

/**
 * Card hash calculated by schema described in method description
 * @member {String} card
 */
SecuresaleFields.prototype['card'] = undefined;






export default SecuresaleFields;

