/**
 * Tpay.com Technical Documentation
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: pt@tpay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TpayComTechnicalDocumentation);
  }
}(this, function(expect, TpayComTechnicalDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TpayComTechnicalDocumentation.CreateFields();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateFields', function() {
    it('should create an instance of CreateFields', function() {
      // uncomment below and update the code to test CreateFields
      //var instane = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be.a(TpayComTechnicalDocumentation.CreateFields);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property crc (base name: "crc")', function() {
      // uncomment below and update the code to test the property crc
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property md5sum (base name: "md5sum")', function() {
      // uncomment below and update the code to test the property md5sum
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property group (base name: "group")', function() {
      // uncomment below and update the code to test the property group
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property resultUrl (base name: "result_url")', function() {
      // uncomment below and update the code to test the property resultUrl
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property resultEmail (base name: "result_email")', function() {
      // uncomment below and update the code to test the property resultEmail
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property merchantDescription (base name: "merchant_description")', function() {
      // uncomment below and update the code to test the property merchantDescription
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property customDescription (base name: "custom_description")', function() {
      // uncomment below and update the code to test the property customDescription
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property returnUrl (base name: "return_url")', function() {
      // uncomment below and update the code to test the property returnUrl
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property returnErrorUrl (base name: "return_error_url")', function() {
      // uncomment below and update the code to test the property returnErrorUrl
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property zip (base name: "zip")', function() {
      // uncomment below and update the code to test the property zip
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property acceptTos (base name: "accept_tos")', function() {
      // uncomment below and update the code to test the property acceptTos
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

    it('should have the property apiPassword (base name: "api_password")', function() {
      // uncomment below and update the code to test the property apiPassword
      //var instance = new TpayComTechnicalDocumentation.CreateFields();
      //expect(instance).to.be();
    });

  });

}));
